---

- name: Get version
  when: snappymail_version == 'latest'
  block:

    - name: Get latest release of a public repository
      ansible.builtin.uri:
        url: "{{ snappymail_api + '/releases/latest' }}"
      check_mode: no
      register: snappymail_release_latest

    - name: Register the version only
      ansible.builtin.set_fact:
        snappymail_version: "{{ snappymail_release_latest['json']['name'] | regex_replace('^v') }}"

- name: Install packages
  ansible.builtin.package:
    name: "{{ snappymail_packages }}"
    state: present

- name: Create snappymail directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ snappymail_user }}"
    group: "{{ snappymail_group }}"
    mode: "0755"
  loop:
    - "{{ snappymail_path }}"
    - "{{ snappymail_data_path }}"
    - "{{ snappymail_log }}"

- name: Setup alternative data location
  when: snappymail_data_path != snappymail_path+'/data'
  block:

    - name: Create snappymail directories
      ansible.builtin.file:
        path: "{{ snappymail_data_path }}/data"
        state: directory
        owner: "{{ snappymail_user }}"
        group: "{{ snappymail_group }}"
        mode: "0755"

    - name: Create temporary symbolic link
      ansible.builtin.file:
        src: "{{ snappymail_data_path }}"
        dest: "{{ snappymail_path }}/data"
        state: link
      tags:
        - molecule-idempotence-notest

- name: Extract the software
  ansible.builtin.unarchive:
    src: "{{ snappymail_url }}"
    dest: "{{ snappymail_path }}"
    owner: "{{ snappymail_user }}"
    group: "{{ snappymail_group }}"
    mode: "0755"
    remote_src: true
  check_mode: no
  changed_when: false

- name: Change ownership
  ansible.builtin.file:
    path: "{{ snappymail_path }}"
    owner: "{{ snappymail_user }}"
    group: "{{ snappymail_group }}"
    recurse: true
  check_mode: no
  changed_when: false

- name: Set SELinux labels
  community.general.sefcontext:
    target: '{{ item.target }}'
    setype: '{{ item.setype }}'
    state: present
  with_items:
    - { target: '{{ snappymail_path }}(/.*)?', setype: httpd_sys_content_t }
    - { target: '{{ snappymail_data_path }}(/.*)?', setype: httpd_sys_rw_content_t }
  notify: Restarting web service
  when:
    - ansible_os_family == 'RedHat'
    - ansible_facts.selinux.status == 'enabled'
